# Generated by Django 4.0.1 on 2022-02-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
