# Generated by Django 4.0.1 on 2022-02-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='other',
            new_name='account',
        ),
    ]
