# Generated by Django 4.0.1 on 2022-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_code_alter_bill_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
