# Generated by Django 4.0.1 on 2022-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='code',
        ),
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
