# Generated by Django 4.0.1 on 2022-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_bill_code_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
