# Generated by Django 4.0.1 on 2022-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
