# Generated by Django 4.0.1 on 2022-02-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='deleted_at',
            new_name='canceled_at',
        ),
    ]
