# Generated by Django 4.0.1 on 2022-01-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_gategory_alter_product_note_product_gategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gategory',
            new_name='category',
        ),
    ]
